persistence:
  type: pvc
  enabled: true
datasources: 
 datasources.yaml:
   apiVersion: 1
   datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-read.grafana.svc.cluster.local:3100
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.grafana.svc.cluster.local:80
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.grafana.svc.cluster.local:3100
      jsonData:
        tracesToLogsV2:
          datasourceUid: 'Loki'
          tags: ['job', 'instance', 'pod', 'namespace']
        tracesToMetrics:
          datasourceUid: 'Prometheus'

adminUser: admin
adminPassword: strongpassword123

dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards

dashboards:
  default:
    kube-namespace:
      gnetId: 15758
      datasource: Prometheus
      revision: 1
    loki-logs:
      gnetId: 16976
      datasource: Loki
      revision: 1
    http-services:
      gnetId: 21587
      datasource: LokiPrometheusTempo
      revision: 1
#  prometheus-stats:
#    gnetId: 2
#    revision: 2
#    datasource: prometheus
#  kubernetes-cluster-monitoring:
#    gnetId: 1621
#    revision: 1
#    datasource: prometheus
#  kubernetes-resource-requests:
#    gnetId: 7187
#    revision: 1
#    datasource: prometheus
#  kubernetes-capacity:
#    gnetId: 5309
#    revision: 1
#    datasource: prometheus
#  kubernetes-pods:
#    gnetId: 6336
#    revision: 1
#    datasource: Prometheus
#  kubernetes-cluster:
#    gnetId: 6417
#    revision: 1
#    datasource: prometheus