persistence:
  type: pvc
  enabled: true
datasources: 
 datasources.yaml:
   apiVersion: 1
   datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-read.grafana.svc.cluster.local:3100
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.grafana.svc.cluster.local:80
    - name: tempo
      type: tempo
      access: proxy
      url: http://tempo.grafana.svc.cluster.local:3100

adminUser: admin
adminPassword: strongpassword123