tempo:
  metricsGenerator:
    # -- If true, enables Tempo's metrics generator (https://grafana.com/docs/tempo/next/metrics-generator/)
    enabled: false
    remoteWriteUrl: "http://prometheus-prometheus-pushgateway.grafana.svc.cluster.local:9090/api/v1/write"

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

metrics_generator:
  processor:
    service_graphs:
      enable_virtual_node_label: true
    span_metrics:
      filter_policies:
        - include:
            match_type: strict
            attributes:
              - key: kind
                value: SPAN_KIND_SERVER

  storage:
    remote_write:
      url: http://prometheus-prometheus-pushgateway.grafana.svc.cluster.local:9091