apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.*
    helm:
      valueFiles:
      - $values/values.yaml
  - repoURL: 'https://github.com/kamo-semonyo/argo-play.git'
    targetRevision: main
    # path: values.yaml
    ref: values