apiVersion: v1
items:
- apiVersion: v1
  data:
    admin-password: ZTFuMlhITGI0cFBZQ0J3U1d0aU9ZeUxIWWVLZHo1YVVzeENCald5WQ==
    admin-user: YWRtaW4=
    ldap-toml: ""
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"admin-password":"ZTFuMlhITGI0cFBZQ0J3U1d0aU9ZeUxIWWVLZHo1YVVzeENCald5WQ==","admin-user":"YWRtaW4=","ldap-toml":""},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"11.3.1","argocd.argoproj.io/instance":"grafana","helm.sh/chart":"grafana-8.6.4"},"name":"grafana","namespace":"grafana"},"type":"Opaque"}
    creationTimestamp: "2024-12-12T06:01:03Z"
    labels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 11.3.1
      argocd.argoproj.io/instance: grafana
      helm.sh/chart: grafana-8.6.4
    name: grafana
    namespace: grafana
    resourceVersion: "17116"
    uid: b07c54fd-d87d-41ca-95e8-885641ab0baf
  type: Opaque
- apiVersion: v1
  data:
    admin-password: ZTFuMlhITGI0cFBZQ0J3U1d0aU9ZeUxIWWVLZHo1YVVzeENCald5WQ==
    admin-user: YWRtaW4=
    ldap-toml: ""
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"admin-password":"ZTFuMlhITGI0cFBZQ0J3U1d0aU9ZeUxIWWVLZHo1YVVzeENCald5WQ==","admin-user":"YWRtaW4=","ldap-toml":""},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"grafana","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"11.3.1","argocd.argoproj.io/instance":"grafana","helm.sh/chart":"grafana-8.6.4"},"name":"grafana","namespace":"grafana"},"type":"Opaque"}
    creationTimestamp: "2024-12-12T06:01:03Z"
    labels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 11.3.1
      argocd.argoproj.io/instance: grafana
      helm.sh/chart: grafana-8.6.4
    name: grafana
    namespace: grafana
    resourceVersion: "17116"
    uid: b07c54fd-d87d-41ca-95e8-885641ab0baf
  type: Opaque
kind: List
metadata:
  resourceVersion: ""

# e1n2XHLb4pPYCBwSWtiOYyLHYeKdz5aUsxCBjWyY